[package]
name = "esa-policy"
version.workspace = true
edition.workspace = true

[dependencies]
esa-core = { path = "../esa-core" }
esa-state = { path = "../esa-state" }

serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
tokio.workspace = true

[dev-dependencies]
esa-gateway = { path = "../esa-gateway" }
